{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "platform-common.fullname" . }}-secrets
  labels: {{- include "platform-common.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef: {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "platform-common.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.remoteRefs }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .key }}
        {{- with .property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
